server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

      routes:
        - id: formularios-service
          uri: lb://formularios-service
          predicates:
            - Path=/api/formularios/**

        - id: usuarios-service
          uri: lb://usuarios-service
          predicates:
            - Path=/api/**

        - id: juegos-service
          uri: http://localhost:9094
          predicates:
            - Path=/api/juegos/**
          filters:
            - RewritePath=/api/juegos/(?<segment>.*), /games/${segment}

        - id: metricas-service
          uri: lb://metricas-service
          predicates:
            - Path=/api/metricas/**

      httpserver:
        max-header-size: 65536

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
